# Site settings
title: Portfolio
description: Some things about me
# baseurl: /portfolio
# url: 

# User settings
username: Nisha 
user_description: Learning new things
user_title: Masters Student in Computer Science
email: paris.nisha@gmail.com 
github_username:  codeanddraw 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
