# Site settings
title: Portfolio
description: Know me
# baseurl: /portfolio
# url: 

# User settings
username: Nisha Learner
user_description: Learning new things
user_title: Software Developer
email: paris.nisha@gmail.com
twitter_username: 
github_username:  codeanddraw
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
